#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# Создайте списки:

# моя семья (минимум 3 элемента, есть еще дедушки и бабушки, если что)
my_family = ['dad', 'mom', 'uncle']

# список списков приблизителного роста членов вашей семьи
my_family_height = [['dad', 1.83], ['mom', 1.65], ['uncle', 1.75]]

# Выведите на консоль рост отца в формате
x = 'рост отца - '
y = ' см'
print(x + str(my_family_height[0][1]) + y)

# Выведите на консоль общий рост вашей семьи как сумму ростов всех членов
#   Общий рост моей семьи - ХХ см
z = 'Общий рост моей семьи - '
dad1 = my_family_height[0][1]
mom1 = my_family_height[1][1]
uncle1 = my_family_height[2][1]
sum_age = dad1 + mom1 + uncle1

print(z + str(sum_age) + y)


